apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wag4p6k63-python 
  janus-idp.io/tekton: wag4p6k63-python
  backstage.io/kubernetes-id: wag4p6k63-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wag4p6k63-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  